### ISSUE TITLE
Data folder is not getting copied in EAP package

### ISSUE THREAD

**Issue by axisvivek** [trunnion/cargo-acap#6]
Data folder is not getting copied in EAP package. Do I need to mention this folder somewhere?

![image](https://user-images.githubusercontent.com/52032125/183016724-a1294c4e-5b08-4167-8f43-800c12074813.png)

**Comment by sinnrrr** [comment]
@axisvivek this feature currently is not implemented in this repo, however, you can use my fork until it will be merged into here.

https://github.com/sinnrrr/cargo-acap
