### ISSUE TITLE
Dashes in the crate name causes repeated crashes on acap installation

### ISSUE THREAD

**Issue by karlri** [trunnion/cargo-acap#7]
If a binary crate is called for example "something-test", installation of the acap fails and repeated crashes occur in Axis FW about parsing the .conf file. Removing the '-' in the crate name mitigates the issue.

**Comment by karlri** [comment]
It seems that subsequent boot of the Axis device will fail after attempted installation of an acap with an unparseable .conf file. This will be reported to Axis.

**Comment by willglynn** [comment]
Well, that's… neat. I know there's shell interpolation gotchas (or opportunities!) too.

What should we do about this here?

**Comment by karlri** [comment]
I plan on submitting a fix for this shortly with a text transformation that mitigates the issue on older FW. I thought in the meanwhile its useful if people are informed about this and how to mitigate it.

**Comment by willglynn** [comment]
Fixed via #8, released as `cargo-acap` 0.1.2.
