### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by johan-bjareholt** [trunnion/cargo-acap#9]
I want to know what rights and requirements I have when modifying, distributing and runningcode from this project.

**Comment by willglynn** [comment]
The `Cargo.toml` specifies [MIT OR Apache-2.0](https://github.com/trunnion/cargo-acap/blob/master/Cargo.toml#L8), aligning with `cargo` and `rustc`, but you're right that the license files are not themselves in this repo.

`cargo-acap` imposes no license requirements on the resulting binaries.
